language: python
dist: xenial
sudo: required

python:
  - "2.7.14"

addons:
#  code_climate:
#    repo_token: f7fa84853f7688638c4692deda36f9c85b4c4099fd42da5a6e7097c2f29cd651
  postgresql: "9.5"
  apt:
    packages:
    - libpq5=9.5.13-0ubuntu0.16.04
    - libpq-dev=9.5.13-0ubuntu0.16.04
    - python-psycopg2
    - apache2
    - apache2-dev

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - touch monitor/monitor/passwords.py
  - psql -c 'create database monitor;' -U postgres
  - python monitor/manage.py makemigrations 
  - python monitor/manage.py migrate 
  - python monitor/manage.py makemigrations app 
  - python monitor/manage.py migrate app
  - npm install karma
  - npm install karma-browserstack-launcher --save-dev

script:
  - python monitor/manage.py test
  - coverage run monitor/manage.py test
#  - simon-javascript/node_modules/karma/bin/karma start simon-javascript/my.conf.js --single-run

after_success: coveralls

notifications:
  slack: lacnic-eng:jSDKPP0pyOgA5JV4lsQTGtuP
